---

# Tasks file for copying nginx.repo file

# Copy nginx.repo file
  - name: Copy nginx.repo
    copy:
      src: ./scripts/nginx/nginx.repo
      dest: /etc/yum.repos.d/nginx.repo
      mode: 0644

# Install nginx from repo
  - name: Install nginx
    yum :
      name: nginx
      state: latest

# Copy nginx default.conf
  - name: Copy nginx default.conf
    copy:
      src: ./scripts/nginx/default.conf
      dest: /etc/nginx/conf.d/default.conf
      mode: 0644

# Retart nginx
  - name: Reload nginx
    systemd:
      name: nginx
      state: reloaded
